package com.telcordia.inpac.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-08-02T11:35:20.148+07:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "NPCWebService", 
                  wsdlLocation = "file:/E:/VNM/SpringToolSuite/wsdl/conf/hf_services.wsdl",
                  targetNamespace = "http://ws.inpac.telcordia.com") 
public class NPCWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.inpac.telcordia.com", "NPCWebService");
    public final static QName NPCWebServiceHttpSoap12Endpoint = new QName("http://ws.inpac.telcordia.com", "NPCWebServiceHttpSoap12Endpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/VNM/SpringToolSuite/wsdl/conf/hf_services.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NPCWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/VNM/SpringToolSuite/wsdl/conf/hf_services.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NPCWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NPCWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NPCWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NPCWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NPCWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NPCWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns NPCWebServicePortType
     */
    @WebEndpoint(name = "NPCWebServiceHttpSoap12Endpoint")
    public NPCWebServicePortType getNPCWebServiceHttpSoap12Endpoint() {
        return super.getPort(NPCWebServiceHttpSoap12Endpoint, NPCWebServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NPCWebServicePortType
     */
    @WebEndpoint(name = "NPCWebServiceHttpSoap12Endpoint")
    public NPCWebServicePortType getNPCWebServiceHttpSoap12Endpoint(WebServiceFeature... features) {
        return super.getPort(NPCWebServiceHttpSoap12Endpoint, NPCWebServicePortType.class, features);
    }

}
